site_name: 2ch /ai/ wiki
site_url: https://2ch-ai.gitgud.site/wiki
repo_url: https://gitgud.io/2ch-ai/wiki
theme:
  name: material
nav:
  - Шапка NAI-треда: ./nai/shapka.md
  - 2chAI easy LORA guide: ./nai/2chAI_easy_LORA_guide.md
  - 2ch NAI guide: ./nai/2ch_nai_guide.md
