site_name: 2ch /ai/ wiki
site_url: https://2ch-ai.gitgud.site/wiki

repo_url: https://gitgud.io/2ch-ai/wiki/
edit_uri: -/edit/master/docs/

theme:
  name: material
  language: ru
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.expand
    - content.tooltips
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - assets/css/extended-markdown.css

markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
      permalink_title: Постоянная ссылка
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

nav:
  - /nai/:
    - Шапка NAI-треда: ./nai/nai-shapka.md
    - FAQ: ./nai/nai-faq.md
    - 2ch NAI guide: ./nai/2ch_nai_guide.md
    - Гайды по обучению лор:
      - 2chAI easy LORA guide: ./nai/lora/2chAI_easy_LORA_guide.md
      - 2chAI hard LORA guide: ./nai/lora/2chAI_hard_LoRA_guide.md
      - Старый гайд по обучению: ./nai/lora/2chAI_LoRA_Dreambooth_guide_old.md
  - /tech/:
    - Шапка технотреда: ./tech/tech-shapka.md
    - Lycoris: ./tech/lycoris.md
    - Обучение SDXL: ./tech/sdxl.md
    - Обучение YOLO: ./tech/yolo.md
    - Legacy ссылки: ./tech/legacy.md
    - Архивы тредов: ./tech/old_threads.md
  - /speech/:
    - Общее: ./speech/index.md
    - Text To Speech:
      - Silero: ./speech/tts/silero.md
      - XTTS: ./speech/tts/xtts.md
      - Edge: ./speech/tts/edge.md
      - VITS-Umamusume-voice-synthesizer: ./speech/tts/vits-umamusume-voice-synthesize.md
      - MoeGoe и MoeTTS: ./speech/tts/moe.md
    - Speech To Speech:
      - RVC:
        - Общее: ./speech/sts/rvc/rvc.md
        - Использование RVC: ./speech/sts/rvc/rvc-usage.md
      - SVC:
        - Общее: ./speech/sts/svc/svc.md
        - Использование SVC: ./speech/sts/svc/svc-usage.md
    - Шапка голосового треда: ./speech/speech-shapka.md
